config:
  fix: true

# MD013/line-length - Line length
MD013:
  line_length: 120
  tables: false
  ignore_code_blocks: true

MD033:
  allowed_elements:
    - GH # This isn't an element but is detected as such in the template
